export const PALETTE_OPTIONS = [
  "hand-tool",
  "lasso-tool",
  "space-tool",
  "global-connect-tool",
  "tool-separator",
  "create.exclusive-gateway",
  "create.start-event",
  "create.intermediate-event",
  "create.end-event",
  "create.exclusive-gateway",
  "create.task",
  //"create.subprocess-expanded",
  "create.data-object",
];
